#!/usr/bin/python3

def raise_exception_msg(msg=""):
    try:
        print(nam)
    except NameError:
        raise NameError(msg)
